[package]
name = "shaders"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
bytemuck = "1.21.0"
gl = "0.14.0"
glfw = "0.59.0"
glm = "0.2.3"
nalgebra = "0.33.2"
wgpu = "23.0.1"
winit = "0.30.5"
